=== NicoleZambrano02/SOA-LABORATORIO-CASA-6/src/java/SALAMI/tareaDesafioXSD.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="producto">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="codigo" type="xs:string"/>
                <xs:element name="nombre" type="xs:string"/>
                <xs:element name="descripcion">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="color" type="xs:string"/>
                            <xs:element name="peso" type="xs:string"/>
                            <xs:element name="fecha_ingreso" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="cantidad" type="xs:integer"/>
                <xs:element name="proveedor" type="xs:string"/>
                <xs:element name="tipo" type="xs:string"/>
                <xs:element name="tipo2" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== NicoleZambrano02/SOA-LABORATORIO-CASA-6/src/java/SALAMI/tareaDesafio.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<producto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="tareaDesafioXSD.xsd">
    <codigo>12345</codigo>
    <nombre>DETERGENTE-FAB</nombre>
    <descripcion>
        <color>AZUL</color>
        <peso>14gramos</peso>
        <fecha_ingreso>2018-11-16</fecha_ingreso>
    </descripcion>
    <cantidad>33</cantidad>
    <proveedor>VERMONTIA</proveedor>
    <tipo>LIM</tipo>
    <tipo2>dLp</tipo2>
</producto>
